"""fix(reservations): ajuste de tabla para levantar la restriccion

Revision ID: 054ef20af074
Revises: 6862ff3560dd
Create Date: 2026-03-16 10:21:14.252339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '054ef20af074'
down_revision: Union[str, None] = '6862ff3560dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservations', 'table_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('reservations_table_id_fkey', 'reservations', type_='foreignkey')
    op.create_foreign_key(None, 'reservations', 'tables', ['table_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.create_foreign_key('reservations_table_id_fkey', 'reservations', 'tables', ['table_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('reservations', 'table_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
