"""allow null table_id and set on delete set null

Revision ID: 6862ff3560dd
Revises: d1799a25134d
Create Date: 2026-03-16 08:22:27.475665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6862ff3560dd'
down_revision: Union[str, None] = 'd1799a25134d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservations', 'table_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('reservations_table_id_fkey', 'reservations', type_='foreignkey')
    op.create_foreign_key(None, 'reservations', 'tables', ['table_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.create_foreign_key('reservations_table_id_fkey', 'reservations', 'tables', ['table_id'], ['id'], ondelete='SET NULL')
    op.alter_column('reservations', 'table_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
